SSCS 6853 added sscs shared infra instrument key
hmcts/sscs-cor-backend pull request #522
Opened 2019-12-03 16:39 UTC by chrisdavecm

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-6853

### Change description ###
add logging for alerts

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2019-12-04 12:20 UTC, jackmaloney requested changes

2019-12-04 12:20 UTC, jackmaloney commented on infrastructure/aat.tfvars
> +appinsights_instrumentation_key = "e2300a5f-a16f-4657-a63b-41913805661e"
Not sure this is the right way to do this in AKS. Platform Engineering previously advised that app insights key should be loaded in through secrets e.g. https://github.com/hmcts/sscs-ccd-callback-orchestrator/blob/master/charts/sscs-ccd-callback-orchestrator/values.yaml#L19 . You would also need to remove this from Flux as well: https://github.com/hmcts/cnp-flux-config/blob/master/k8s/aat/common/sscs/sscs-cor-backend.yaml#L22

2019-12-09 16:30 UTC, jackmaloney submitted a review, later dismissed

2019-12-10 12:52 UTC, jackmaloney submitted a review, later dismissed

2019-12-16 12:49 UTC, iguannago approved these changes

2019-12-16 13:19 UTC, merged